version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    # ... existing config ...

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    # ... existing config ...

  redis:  # NEW for dashboard caching
    image: redis:alpine
    ports:
      - "6379:6379"

  dashboard:  # NEW Flask service
    build: ./dashboard
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - redis
    environment:
      - FLASK_ENV=development
