# This tells Docker to build two radio towers:
# 1. Zookeeper (the operator)
# 2. Kafka (the walkie-talkie)
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    ports: ["2181:2181"]
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    ports: ["9092:9092"]
    depends_on: [zookeeper]
